name: Security - Opengrep

on:
  push:
    branches:
      - master
      - main 
      - develop
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - master
      - main
      - develop
      - 'release/**'
      - 'hotfix/**'
  workflow_call:

permissions:
  contents: read
  security-events: write
  actions: read

env:
  # Release version of Opengrep
  # https://github.com/opengrep/opengrep/releases
  RELEASE_VERSION: v1.4.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Download / Install Opengrep"
        run: |
          set -e

          echo "[+] Downloading Opengrep"
          curl -sSfL \
            -o "/usr/local/bin/opengrep" \
            "https://github.com/opengrep/opengrep/releases/download/${RELEASE_VERSION}/opengrep_manylinux_x86"
          chmod +x /usr/local/bin/opengrep
          echo "[+] Finished installing opengrep"

      - name: "Run Opengrep"
        run: opengrep scan --metrics=on --sarif-output ./results.sarif .

      - name: "Upload SARIF file"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
        if: always()
